### ISSUE TITLE
Messages while installing

### ISSUE THREAD

**Issue by marcelloh** [bykof/go-plantuml#1]
When I install, I've got the following "disturbing" messages:
# cd /Users/marcelloh/go/src/golang.org/x/sys; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
error: The following untracked working tree files would be removed by merge:

Please move or remove them before you merge.
Aborting
package golang.org/x/sys/unix: exit status 1

# cd /Users/marcelloh/go/src/gopkg.in/yaml.v2; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
Please commit your changes or stash them before you merge.
Aborting
package gopkg.in/yaml.v2: exit status 1

Totally not what I expect for installing software :-(

**Comment by bykof** [comment]
This looks like a local issue. go-plantuml does nothing special regarding installing things... 
maybe try to remove the folders ~/go/src/gopkg.in/yaml.v2 and ~/go/src/golang.org/x/sys/unix and reinstall again

**Comment by marcelloh** [comment]
This fixed it, thanks. (have another problem, will make new issue)
