### ISSUE TITLE
support generics

### ISSUE THREAD

**Issue by xiaobaiyouxi** [bykof/go-plantuml#17]
Please support generics

**Comment by afmahmuda** [comment]
i am tring to work on this. 

so far i's been able to:
- able to parse ast.IndexExpr struct
- able to render square bracket `[XX]` in plantuml
- skip implementation check if interface is empty (most likely a constraint) 

still thinking on how to:
- add constrains to struct name
- explicitly differentiate constraint and interface

adding this to test folder
```
// test/calculator/models/calculator.go
package calculator

import (
	"github.com/bykof/go-plantuml/test/user/models"
)


type Number interface {
	~int | ~float32
}

type Calculator[T Number] struct {
	owner models.User
}

func (c *Calculator[T]) Add(a, b T) T {
	return a + b
}

func (c *Calculator[T]) Multiply(a, b T) T {
	return a * b
}


```
result 
![image](https://user-images.githubusercontent.com/10903985/201580449-2ab89d1c-30e4-4d87-95b8-bdbd2225fff0.png)

PR : https://github.com/bykof/go-plantuml/pull/24
