### ISSUE TITLE
go-plantuml generate -r gives error

### ISSUE THREAD

**Issue by marcelloh** [bykof/go-plantuml#2]
2020/01/22 13:53:14 unknown Field Type *ast.ChanType

Tried this in several projects

**Comment by bykof** [comment]
Will be fixed soon

**Comment by bykof** [comment]
It's implemented, please reinstall and try again :)

**Comment by marcelloh** [comment]
works. Except.... it's eating my vendor map as well and not I have a pink cloud with far too much lines :-(

**Comment by bykof** [comment]
You can use -d parameter to specify the directories

**Comment by marcelloh** [comment]
Super !!!! Thanks for the info (I must have overlooked that option)
