### ISSUE TITLE
[feature request] excluding files/folder by name

### ISSUE THREAD

**Issue by afmahmuda** [bykof/go-plantuml#20]
**problem** 
currently, only ignore non `.go` files and `_test.go` files
suppose i have `_mock` file inside the same folder, said mock will pollute the the whole graph

**how to reproduce**

generate mock file inside target folder / sub folder

**proposed solution**
1. option to ignore file by name, eg. `^.+mock$`
or 
2. option to ignore `generated` files
or
3. ability to ignore folders

**Comment by afmahmuda** [comment]
before going to implementation, i would like to ask your opinion on which solution will be better, of if you have a better solution

**Comment by bykof** [comment]
Hi @afmahmuda thank you for contributing!
I would rather go with `ignore_regex` where users can ignore folders or files by using a regex.

**Comment by afmahmuda** [comment]
PR created here
https://github.com/bykof/go-plantuml/pull/21

**Comment by bykof** [comment]
Thank again for contribution. 
I think, with the help of yourself, this can be closed :)
