### ISSUE TITLE
Add support for layout direction

### ISSUE THREAD

**Issue by btiernay** [bykof/go-plantuml#27]
A small addition, but can really help improve readability.

**Comment by torbendury** [comment]
+1 on this, even a very small application consisting of a `Server`, a `Storage` and a `Book` as data representation results in a diagram which takes up quite some horizontal space:

![go-plantuml](https://github.com/bykof/go-plantuml/assets/94752317/6ec3e936-b267-4f7a-b343-216facd0d9c3)

**Comment by bykof** [comment]
Hello, thanks for you comment.
Is it better, if you use `left to right direction` right after your `@plantuml` line? 
Can you check and report me please?

**Comment by torbendury** [comment]
Hi @bykof, starting the diagram off with `left to right direction` results in the diagram at [torbendury/book-go](https://github.com/torbendury/books-go#overview).

![graph.puml](https://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/torbendury/books-go/main/docs/graph.puml)

**Comment by bykof** [comment]
Is this what you are looking for? :)

**Comment by torbendury** [comment]
Looks quite like it! Would it be possible to add a flag for controlling the direction? Otherwise it'd be quite a hassle monkey-patching the puml file after autogenerating it :)

**Comment by bykof** [comment]
Is fixed in v1.3.4: https://github.com/bykof/go-plantuml/releases/tag/v1.3.4
