### ISSUE TITLE
Doesn't respect slice of type

### ISSUE THREAD

**Issue by akzincsystems** [bykof/go-plantuml#28]
![image](https://github.com/user-attachments/assets/1d9892da-f335-48fd-9887-9a7f371e28e1)
In the diagram snippet shown, GQLTaskData references GQLTaskNotes and is linked as expected. GQLTaskNotes references a slice, []GQLTaskNotesData but is not linked as expected in the diagram.

GQLTaskNotesData is shown on the diagram
![image](https://github.com/user-attachments/assets/3a3a7165-87b4-4264-8833-dc0be674ddbd)

If you can point me at where this is failing, I'll have a go at fixing myself if you haven't the time.

Cheers
Ashley

**Comment by bykof** [comment]
This is fixed in v1.3.3
